// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnchorIndex: typeof import('./../../../utils-common/components/Anchor/anchorIndex.vue')['default']
    AnchorItem: typeof import('./../../../utils-common/components/Anchor/components/anchorItem.vue')['default']
    EchartsIndex: typeof import('./../../../utils-common/components/Echarts/echartsIndex.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ErrorPage: typeof import('./../../../utils-common/components/Error/errorPage.vue')['default']
    ForbiddenPage: typeof import('./../../../utils-common/components/Error/forbiddenPage.vue')['default']
    HeaderComponent: typeof import('./../components/Header/headerComponent.vue')['default']
    HeaderComponentMenu: typeof import('./../components/Header/menuComponent/headerComponentMenu.vue')['default']
    OrganiseItem: typeof import('./../../../utils-common/components/SelectOrganize/components/OrganiseItem.vue')['default']
    RectangleLoading: typeof import('./../../../utils-common/components/Loading/rectangleLoading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectOrganizeIndex: typeof import('./../../../utils-common/components/SelectOrganize/SelectOrganizeIndex.vue')['default']
    SpaceIndex: typeof import('./../../../utils-common/components/Space/spaceIndex.vue')['default']
    ToolsComponentIndex: typeof import('./../components/Header/toolsComponent/toolsComponentIndex.vue')['default']
    ToolsComponentUser: typeof import('./../components/Header/toolsComponent/toolsComponentUser.vue')['default']
    TreeTable: typeof import('./../../../utils-common/components/TreeTable/TreeTable.vue')['default']
    TreeTableCard: typeof import('./../../../utils-common/components/TreeTable/treeTableCard.vue')['default']
    WujieVue: typeof import('./../../../utils-common/components/Monorepo/WujieVue.vue')['default']
  }
}
