import { MockMethod } from 'vite-plugin-mock';
import { NetState, NetStateMsg } from '@packages/utils-common/enum/index';

export default [
  {
    url: '/admin/menu/routes',
    method: 'get',
    // statusCode: NetState.NOAUTH,
    response: () => {
      return {
        code: NetState.OK,
        msg: NetStateMsg.OK,
        data: [
          // 系统管理
          {
            children: [
              {
                children: [],
                component: 'Menu/menuIndex',
                meta: {
                  icon: 'install',
                  target: true,
                  title: '菜单管理',
                  type: 'M',
                },
                name: 'menu ',
                path: '/menu',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'User/userIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '用户管理',
                  type: 'M',
                },
                name: 'user ',
                path: '/user',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Dept/deptIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '部门管理',
                  type: 'M',
                },
                name: 'dept ',
                path: '/dept',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Occupation/occupationIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '岗位管理',
                  type: 'M',
                },
                name: 'occupation ',
                path: '/occupation',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Role/roleIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '角色管理',
                  type: 'M',
                },
                name: 'role',
                path: '/role',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Dict/dictIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '数据字典',
                  type: 'M',
                },
                name: 'dict',
                path: '/dict',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Version/versionIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '版本管理',
                  type: 'M',
                },
                name: 'version',
                path: '/version',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Notice/noticeIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '通知公告',
                  type: 'M',
                },
                name: 'notice',
                path: '/notice',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'LowCode/lowCodeIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '代码生成',
                  type: 'M',
                },
                name: 'lowCode',
                path: '/lowCode',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'Log/logIndex',
                meta: {
                  icon: 'avatar',
                  target: true,
                  title: '日志查看',
                  type: 'M',
                },
                name: 'log',
                path: '/log',
                updateTime: '@natural(0,300)',
              },
            ],
            component: 'system',
            meta: {
              icon: 'install',
              target: true,
              preset: false,
              title: '系统管理',
              type: 'S',
            },
            name: 'system',
            path: 'http://localhost:7790',
            updateTime: '@natural(0,300)',
          },
          {
            children: [],
            component: 'archive',
            meta: {
              icon: 'trophy',
              target: true,
              preset: false,
              title: '灾损评估',
              type: 'S',
            },
            name: 'archive ',
            path: 'http://localhost:7791',
            updateTime: '@natural(0,300)',
          },
          {
            children: [],
            component: 'emergency',
            meta: {
              icon: 'lark',
              target: true,
              preset: false,
              title: '应急指挥',
              type: 'S',
            },
            name: 'emergency ',
            path: 'http://localhost:7792',
            updateTime: '@natural(0,300)',
          },
          {
            children: [
              {
                children: [
                  {
                    children: [
                      {
                        children: [],
                        component: 'station/stationIndex',
                        meta: {
                          icon: 'trophy',
                          target: true,
                          preset: false,
                          title: '监测站管理',
                          type: 'M',
                        },
                        name: 'station',
                        path: '/station',
                        updateTime: '@natural(0,300)',
                      },
                      {
                        children: [],
                        component: 'equipment/equipmentIndex',
                        meta: {
                          icon: 'trophy',
                          target: true,
                          preset: false,
                          title: '设备管理',
                          type: 'M',
                        },
                        name: 'equipment',
                        path: '/equipment',
                        updateTime: '@natural(0,300)',
                      },
                      {
                        children: [],
                        component: 'creature/creatureIndex',
                        meta: {
                          icon: 'trophy',
                          target: true,
                          preset: false,
                          title: '生物基础库管理',
                          type: 'M',
                        },
                        name: 'creature',
                        path: '/creature',
                        updateTime: '@natural(0,300)',
                      },
                      {
                        children: [],
                        component: 'quadrat/quadratIndex',
                        meta: {
                          icon: 'trophy',
                          target: true,
                          preset: false,
                          title: '样方管理',
                          type: 'M',
                        },
                        name: 'quadrat',
                        path: '/quadrat',
                        updateTime: '@natural(0,300)',
                      },
                      {
                        children: [
                          {
                            children: [],
                            component: 'led/ledMachineIndex',
                            meta: {
                              icon: 'trophy',
                              target: true,
                              preset: false,
                              title: 'LED设备管理',
                              type: 'M',
                            },
                            name: 'ledMachine',
                            path: '/ledMachine',
                            updateTime: '@natural(0,300)',
                          },
                          {
                            children: [],
                            component: 'led/ledTemplateIndex',
                            meta: {
                              icon: 'trophy',
                              target: true,
                              preset: false,
                              title: 'LED模版管理',
                              type: 'M',
                            },
                            name: 'ledTemplate',
                            path: '/ledTemplate',
                            updateTime: '@natural(0,300)',
                          },
                        ],
                        component: 'layoutIndex',
                        meta: {
                          icon: 'trophy',
                          target: true,
                          preset: false,
                          title: 'LED',
                          type: 'F',
                        },
                        name: 'led',
                        path: '/layoutIndex',
                        updateTime: '@natural(0,300)',
                      },
                    ],
                    component: 'layoutIndex',
                    meta: {
                      icon: 'trophy',
                      target: true,
                      preset: false,
                      title: '生态监测',
                      type: 'F',
                    },
                    name: 'stjc',
                    path: 'layoutIndex',
                    updateTime: '@natural(0,300)',
                  },
                  {
                    children: [
                      {
                        children: [],
                        component: 'resource/resourceIndex',
                        meta: {
                          icon: 'trophy',
                          target: true,
                          preset: false,
                          title: '资源类型管理',
                          type: 'M',
                        },
                        name: 'resource',
                        path: '/resource',
                        updateTime: '@natural(0,300)',
                      },
                    ],
                    component: 'layoutIndex',
                    meta: {
                      icon: 'trophy',
                      target: true,
                      preset: false,
                      title: '资源分布',
                      type: 'F',
                    },
                    name: 'zyfb',
                    path: 'layoutIndex',
                    updateTime: '@natural(0,300)',
                  },
                  {
                    children: [],
                    component: 'layoutIndex',
                    meta: {
                      icon: 'trophy',
                      target: true,
                      preset: false,
                      title: '森林防火',
                      type: 'M',
                    },
                    name: 'slfh',
                    path: 'layoutIndex',
                    updateTime: '@natural(0,300)',
                  },
                  {
                    children: [],
                    component: 'layoutIndex',
                    meta: {
                      icon: 'trophy',
                      target: true,
                      preset: false,
                      title: '全系感知',
                      type: 'M',
                    },
                    name: 'qxgz',
                    path: 'layoutIndex',
                    updateTime: '@natural(0,300)',
                  },
                  {
                    children: [],
                    component: 'layoutIndex',
                    meta: {
                      icon: 'trophy',
                      target: true,
                      preset: false,
                      title: '科研宣教',
                      type: 'M',
                    },
                    name: 'kyxj',
                    path: 'layoutIndex',
                    updateTime: '@natural(0,300)',
                  },
                ],
                component: 'DataVault',
                meta: {
                  icon: 'trophy',
                  target: true,
                  preset: false,
                  title: '数据管理',
                  type: 'S',
                },
                name: 'DataVault',
                path: 'http://localhost:7793',
                updateTime: '@natural(0,300)',
              },
              {
                children: [],
                component: 'DataScope',
                meta: {
                  icon: 'trophy',
                  target: true,
                  preset: false,
                  title: '数据视图',
                  type: 'S',
                },
                name: 'DataScope',
                path: 'http://localhost:7799',
                updateTime: '@natural(0,300)',
              },
            ],
            component: 'dataHub',
            meta: {
              icon: 'trophy',
              target: true,
              preset: true,
              title: '数据中心',
              type: 'M',
            },
            name: 'dataHub ',
            path: 'layoutIndex',
            updateTime: '@natural(0,300)',
          },
          {
            children: [
              {
                children: [],
                component: 'iconList',
                meta: {
                  icon: 'trophy',
                  target: true,
                  preset: false,
                  title: '图标库',
                  type: 'M',
                },
                name: 'iconList',
                path: '/iconList',
                updateTime: '@natural(0,300)',
              },
            ],
            component: 'layoutIndex',
            meta: {
              icon: 'trophy',
              target: true,
              preset: false,
              title: '图标库',
              type: 'F',
            },
            name: 'icons',
            path: '/icons',
            updateTime: '@natural(0,300)',
          },
        ],
      };
    },
  },
] as MockMethod[];
