import { MockMethod } from 'vite-plugin-mock';
import { NetState, NetStateMsg } from '@packages/utils-common/enum/index';
import { MenuType } from '@packages/utils-common/enum/menuType';

export default [
  {
    url: '/system/menu',
    method: 'post',
    response: () => {
      return {
        code: NetState.OK,
        msg: NetStateMsg.OK,
        data: {
          // 系统管理
          records: [
            {
              children: [
                {
                  children: [],
                  component: 'Menu/menuIndex',
                  icon: 'install',
                  target: true,
                  title: '菜单管理',
                  cache: false,
                  visible: false,
                  type: MenuType.MENU,
                  sort: 1,
                  id: 'dewfefer23',
                  name: 'menu ',
                  path: '/menu',
                  updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
                  updateBy: '@cname()',
                },
                {
                  children: [
                    {
                      children: [],
                      component: 'User/userIndex',
                      icon: 'avatar',
                      target: true,
                      id: 'dewfferr3',
                      title: '新增',
                      cache: false,
                      sort: 4,
                      visible: false,
                      type: MenuType.BUTTON,
                      name: 'user ',
                      path: '/user',
                      updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
                      updateBy: '@cname()',
                    },
                  ],
                  component: 'User/userIndex',
                  icon: 'avatar',
                  target: true,
                  id: 'dewfefer2fefer3',
                  title: '用户管理',
                  cache: false,
                  sort: 4,
                  visible: false,
                  type: MenuType.MENU,
                  name: 'user ',
                  path: '/user',
                  updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
                  updateBy: '@cname()',
                },
              ],
              component: 'system',
              icon: 'install',
              target: true,
              preset: false,
              sort: 1,
              cache: false,
              id: 'dewfefer2fefer3ferfer',
              visible: false,
              title: '系统管理',
              type: MenuType.SYSTEM,
              name: 'system ',
              path: 'http://localhost:7790',
              updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
              updateBy: '@cname()',
            },
            {
              children: [
                {
                  children: [],
                  component: 'User/userIndex',
                  icon: 'avatar',
                  target: true,
                  id: 'dewfffefeffefefeferr3',
                  title: '新增',
                  cache: false,
                  sort: 4,
                  visible: false,
                  type: MenuType.MENU,
                  name: 'user ',
                  path: '/user',
                  updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
                  updateBy: '@cname()',
                },
              ],
              component: 'archive',
              icon: 'trophy',
              target: true,
              id: 'dewfefer2fefer33453',
              preset: false,
              cache: false,
              visible: false,
              title: '灾损评估',
              sort: 2,
              type: MenuType.SYSTEM,
              name: 'archive ',
              path: 'http://localhost:7791',
              updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
              updateBy: '@cname()',
            },
            {
              children: [],
              component: 'emergency',
              icon: 'lark',
              target: true,
              id: 'dewfefer2fefer365757',
              preset: true,
              sort: 3,
              cache: false,
              visible: false,
              title: '应急指挥',
              type: MenuType.SYSTEM,
              name: 'emergency ',
              path: 'http://localhost:7792',
              updateTime: "@datetime('yyyy-MM-dd HH:mm:ss')",
              updateBy: '@cname()',
            },
          ],
          total: 3,
          size: 10,
          current: 1,
        },
      };
    },
  },
] as MockMethod[];
